# Set the maximum line length to 120
line-length = 120

# Additional file extensions
extend-include = ["*.ipynb"]

[lint]
# Add the flake8-annotations rules
select = ["ANN"]

# Exclude checks that function arguments are annotated with a more specific type than Any
ignore = ["ANN401", "ANN101"]

# Add the `line-too-long` rule to the enforced rule set
# By default, Ruff omits rules that overlap with the use of a formatter, like Black,
# but we can override this behavior by explicitly adding the rule
extend-select = ["E501", "F401"]

[format]
# Use single quotes for non-triple-quoted strings
quote-style = "single"