api: "sncloud" # set either sncloud or sambastudio 

embedding_model: 
    "type": "cpu" # set either sambastudio or cpu
    "batch_size": 1 #set depending of your endpoint configuration (1 if bundle embedding expert)
    "bundle": True #set true if using Sambastudio embeddings in a bundle endpoint 
    "select_expert": "e5-mistral-7b-instruct" #set if using SambaStudio bundle embedding expert

llm: 
    "temperature": 0.1
    "max_tokens_to_generate": 1000
    "do_sample": False
    "bundle": True  #set as true if using Sambastudio bundle endpoint
    "select_expert": "llama3-405b" #set if using SambaStudio bundle llm expert
    #sncloud bundle expert name -> "llama3-405b"

retrieval:
    "chunk_size": 500
    "chunk_overlap": 50
    "db_type": "chroma"
    "n_retrieved_documents": 3

query_decomposition:
    "n_generated_subquestions": 3

sec:
    "email": "mlengineer@snova_dummy.ai"
    "company": "snova_dummy"
    "report_type": "10-K"
    "last_n_documents": 1
