name: Python Checks

on: 
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r base_requirements.txt
          pip install ruff mypy
      # Update output format to enable automatic inline annotations.
      - name: Run Ruff Financial Assistant
        run: ruff check --output-format=github financial_assistant
      
      - name: Run MyPy Financial Assistant
        run: mypy --explicit-package-bases financial_assistant
