name: Python Checks

on: 
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: 'pip'
      
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r financial_assistant/requirements.txt
          pip install ruff mypy

      - name: Run Ruff for the Financial Assistant
        run: ruff check --output-format=github financial_assistant
      
      - name: Run MyPy for the Financial Assistant
        run: mypy --explicit-package-bases financial_assistant

      - name: Run Unit Tests for the Financial Assistant
        if: github.event_name == 'pull_request'
        run: |
          python -m unittest discover financial_assistant/tests -k 'test_handle_stock_query'
